name: Hello world
on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'What is your name?'
        required: true 
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Linux
        run: |
          echo "Hello ${{ github.event.inputs.name }}! I'm running on a $(uname -mo) VM."
  windows:
    runs-on: windows-latest
    steps:
      - name: Hello Windows
        shell: pwsh
        run: |
          $os=[System.Environment]::OSVersion.Version
          $cpuArch=$env:PROCESSOR_ARCHITECTURE
          Write-Host "Hello ${{ github.event.inputs.name }}! I'm running on a $cpuArch Windows $($os.Major).$($os.Build) VM."

