name: Teams notification
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build XYZ
      run: echo TODO
  notify:
      runs-on: ubuntu-latest
      if: always()
      needs: build
      steps:
      - name: Send a Notification
        id: notify
        uses: thechetantalwar/teams-notify@v2
        with:
        teams_webhook_url: ${{ secrets.TEAM_HOOK }}
        message: "Github Action Build Number ${{ github.run_number }} Completed for ${{ github.repository }} and the outcome is ${{ needs.build.result }}."
